services:
  - type: web
    name: tariff-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: LC_ALL
        value: C.UTF-8
      - key: LANG
        value: C.UTF-8 